### ISSUE TITLE
Snowflake role with dot (.) in its name can be created but not granted using terraform

### ISSUE THREAD

**Issue by poojagujar93** [Snowflake-Labs/terraform-provider-snowflake#1054]
**Provider Version**

 v0.35.0.

**Terraform Version**

v1.1.8

**Describe the bug**

When using terraform to grant a role to a role/user, the role (snowflake_role) can be created with a dash in the name, but a grant to a role (snowflake_role_grants) with a dot(.) in its name fails with Error: '.' is not a valid identifier character.

**Expected behavior**

A grant should be able to be created for any roles that have been successfully created with snowflake_role.

**Code samples and commands**
# Create Role
resource "snowflake_role" "roles" {
  provider = snowflake.securityadmin
  name     = "DU.DPLTF.DEV.READERS"
  comment  = "this is head of all Dev Readers role"
}

# Grant roles
resource "snowflake_role_grants" "roles" {
  provider   = snowflake.securityadmin
  role_name  = "DU.DPLTF.DEV.READERS"
  roles      = ["sp-terraform"]
  depends_on = [snowflake_role.roles]
}

After running plan:
│ Error: '.' is not a valid identifier character.
│
│   with snowflake_role_grants.grants,
│   on main.tf line 5, in resource "snowflake_role_grants" "grants":
│    5:   role_name   =  "DU.DPLTF.DEV.READERS"
│
╵
time=2022-06-10T16:18:40+05:30 level=error msg=1 error occurred:
        * exit status 1

**Additional context**

If role_name does not have .(dot), then it works. But our projects requirement is to have .(dot) in the role name.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)

Also, check our roadmap, we're going to rework the identifiers because the new grant resources are also using the old identifier code.
