### ISSUE TITLE
Snowflake roles can' start with numbers

### ISSUE THREAD

**Issue by mateuszkoscielny** [Snowflake-Labs/terraform-provider-snowflake#1543]
**Provider Version**

v0.56.4

**Terraform Version**

v1.3.6

**Describe the bug**

When the role that you want to create starts with a number  e.g. 3 you can't run the plan thus can't apply the code.

**Expected behavior**

Allow the creation of roles that start with numbers. As it is allowed to do that thru portal or snowSQL scripts.

**Code samples and commands**
```

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.52"
    }
  }
}
provider "snowflake" {
}
locals {
  admin_role = "${var.tenant}_SYSADMIN"
}
variable "tenant" {
  type    = string
  default = "360"
}
resource "snowflake_role" "sysadmin" {
  name = local.admin_role
}
```

**Additional context**

Issue is halting our project.

**Comment by sfc-gh-swinkler** [comment]
This is definitely an issue that should be fixed. But I would ask that you please file an issue with your Snowflake account representative. It helps us allocate resources to working on your issue.

**Comment by bennylu2** [comment]
@sfc-gh-swinkler what team in Snowflake manages the provider to help with filing issue?

**Comment by sfc-gh-swinkler** [comment]
@bennylu2 there isn't really a "team", as currently the Terraform provider is managed solely by myself, and I am in Cloud engineering, not Support. We would like to move the Terraform provider to the support organization soon, so that it can receive the proper attention that it deserves. This process takes time, however, so I appreciate your patience. 

Meanwhile, it is helpful if you can please let your account representative know that this provider is important to you, and that you would like it to be better supported. That helps us a lot. Also, I am able to prioritize tickets that you file going through the normal support channels. The squeaky wheel gets the grease, so to speak.

**Comment by bennylu2** [comment]
Got it, I have escalated with our account rep. Thanks for the info

**Comment by sfc-gh-mamayo** [comment]
Thanks for the help @sfc-gh-swinkler !
