### ISSUE TITLE
Please revert PR #1522

### ISSUE THREAD

**Issue by philippeboyd** [Snowflake-Labs/terraform-provider-snowflake#1580]
@sfc-gh-swinkler Why was this PR even merged https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1522? It opened up the gates of hell in terms of bugs and new opened issues.

And seriously, emojis in IDs https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1541? 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/3239656/221597247-363e86d2-af93-4d2c-9e8c-efad4ac66827.png">

**Comment by michael-robbins** [comment]
They probably accidentally merged it in before April 1st... might be worth holding off until then

**Comment by sfc-gh-swinkler** [comment]
@philippeboyd there were only a few issues for specific grant (procedures, functions) resources, and these have since been fixed. Note that these issues would have been an problem even without the use of emojis, as I was refactoring the grant resources to make imports and reads and these bugs were something that i failed to account for in the acceptance testing (there are now tests to cover these cases).

Since the resources are currently working, and still supporting the old ID format, I do not see a need to revert the change. I did not introduce emojis for the sake of emojis, i did it as part of a larger refactoring effort on grant ids, and the use of emojis was incidental, as a way to easily discriminate between old and new ids. I am not going to remove emojis just because you do not like them, however I will refrain from using them in the future since this is evidently a divisive issue. 

If you encounter any more bugs please let me know, and I will respond to them, but just saying you do not like something that does not impact the usability of the provider is not constructive feedback.

**Comment by PedroMartinSteenstrup** [comment]
Amazing to have to bookmark somewhere a place to copy paste a snowflake character so that I can write my lines of imports. 🚀 
Looking forward the thousands I have to do in the next weeks. 
Also glad "easily discriminate between old and new ids" could be done at the expense of end-users experience, the ones that actually do use imports 👏 

![image](https://user-images.githubusercontent.com/24451974/222406535-356dabda-4343-43e5-9a57-33c3dc636746.png)

**Comment by philippeboyd** [comment]
> Amazing to have to bookmark somewhere a place to copy paste a snowflake character so that I can write my lines of imports. 🚀 Looking forward the thousands I have to do in the next weeks. Also glad "easily discriminate between old and new ids" could be done at the expense of end-users experience, the ones that actually do use imports 👏
> 
> ![image](https://user-images.githubusercontent.com/24451974/222406535-356dabda-4343-43e5-9a57-33c3dc636746.png)

This is precisely the type of problem I was referring to in my https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1541#issuecomment-1446523775
