### ISSUE TITLE
unable to scan row for SHOW ORGANIZATION ACCOUNTS

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1606]
**Provider Version**

`provider registry.terraform.io/snowflake-labs/snowflake v0.56.0`

**Terraform Version**

`Terraform v1.3.6`

**Describe the bug**

`terraform plan` crashes with this error:

```
│ Error: error reading account: unable to scan row for SHOW ORGANIZATION ACCOUNTS LIKE 'ABC12345' err = missing destination name is_org_admin in *[]snowflake.Account
│ 
│   with module.snowflake_accounts.snowflake_account.account["SOMEACCOUNT"],
│   on ../../modules/aws/snowflake_accounts/main.tf line 28, in resource "snowflake_account" "account":
│   28: resource "snowflake_account" "account" {
```

**Expected behavior**

No error message.

**Code samples and commands**

```
  accounts = [
    "SOMEACCOUNT",
    "SOMEOTHERACCOUNT",
  ]

resource "snowflake_account" "account" {
  for_each             = toset(var.accounts)
  provider             = snowflake.orgadmin
  admin_name           = "AUTOMATION"
  admin_rsa_public_key = replace(trimprefix(trimsuffix(data.tls_public_key.public_key.public_key_pem, "-----END RSA PRIVATE KEY-----\n"), "-----BEGIN RSA PRIVATE KEY-----\n"), "\n", "")
  comment              = "SNOWFLAKE"
  edition              = "BUSINESS_CRITICAL"
  email                = "foo@bar.com"
  first_name           = "First"
  last_name            = "Last"
  name                 = upper(each.value)
  region               = "AWS_US_EAST_1"

  lifecycle {
    ignore_changes = [
      comment
    ]
  }
}


```

**Additional context**

Note that when I run the same query as described in the error message (`SHOW ORGANIZATION ACCOUNTS LIKE 'ABC12345'`) in the Snowflake console, it returns the expected results (1 row). And the `is_org_admin` column evaluates to `false`.

And this Terraform code has been working fine for us for many months, this seemingly just broke randomly.

**Comment by linkages** [comment]
I am having the same problem.
Came in this morning to add some more roles to an existing account and ran into the same issue.

Terraform version:
1.3.9 and 1.1.9

Providers:
0.56.4 and 0.58.0

**Comment by rtdewi0** [comment]
Same issue started today for me after the code has been working for weeks.  Error is:

Error: error reading account: unable to scan row for SHOW ORGANIZATION ACCOUNTS LIKE 'ACCT1234' err = missing destination name is_org_admin in *[]snowflake.Account

Terraform: v1.2.1
Provider versions:  0.56.3 and 0.58.0

**Comment by linkages** [comment]
I've opened a support case with Snowflake and pointed them at this issue for some extra context.

**Comment by rtdewi0** [comment]
I just noticed that according to QUERY_HISTORY_BY_USER in Snowflake the "SHOW ORGANIZATION ACCOUNTS..." statement was working until this morning.  I also noticed that according to QUERY_HISTORY_BY_USER the RELEASE_VERSION went from 7.6.4 to 7.7.4 between the time the query worked and now when it does not.  

I will open a ticket with Snowflake support as well.

**Comment by rtdewi0** [comment]
Per this link, this issue was introduced in the 2023_01 bundle:  [SHOW-ORGANIZATION-ACCOUNTS-New-Column-in-Output](https://community.snowflake.com/s/article/SHOW-ORGANIZATION-ACCOUNTS-New-Column-in-Output)

Snowflake support gave us this as a temporary workaround until a fix for the provider can be made:  

`SELECT SYSTEM$DISABLE_BEHAVIOR_CHANGE_BUNDLE('2023_01');`

**Comment by dstuck** [comment]
Hitting this same issue. I suspect the fix is adding
```
	IsOrgAdmin                        sql.NullString `db:"is_org_admin"`
```
to this account struct: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/d62b1b4d6352e7d2dc99e4603370a1f3de3a4624/pkg/snowflake/account.go#L179

**Comment by sfc-gh-ngaberel** [comment]
Hi everyone, as you suspected this bug was introduced by the addition of the `is_org_admin` column in `SHOW ORGANIZATION ACCOUNTS` in this month's [behavior change release](https://docs.snowflake.com/en/release-notes/2023-03-bcr#show-organization-accounts-command-new-column-in-output) of Snowflake. The fix is in main and will be available in the next release of the provider.
We're looking at ways to detect these API changes earlier internally so we can keep the provider up to date with the future Snowflake releases and prevent this type of issues in the future.
