### ISSUE TITLE
Password Policy Attachment

### ISSUE THREAD

**Issue by marenronneseth** [Snowflake-Labs/terraform-provider-snowflake#1746]
**Is your feature request related to a problem? Please describe.**

Not related to a problem just that Password Policy Attachment in Snowflake isn't available through Terraform.

**Describe the solution you'd like**

I would like to be able to attache Password Policy to an Snowflake account through Terraform . We manage objects like this through Terraform so being able to create and manage this through TF would be helpful.

**Describe alternatives you've considered**

It just isn't available so I don't know of any alternatives

**Additional context**

Link to Snowflake documentation: https://docs.snowflake.com/en/sql-reference/sql/alter-account

**Comment by sfc-gh-ngaberel** [comment]
Hi @marenronneseth, I've added a new `snowflake_account_password_policy_attachment` resource to the provider to support this use case, it will be available with the [next release](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1880), probably by next week.
Please note that, due to a limitation of the SQL API, this resource can only change the password policy of the **current account** (ie. the one specified in the provider block). If you need to change the password policy on a different account you'll need to use an [aliases provider](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations).
