### ISSUE TITLE
Fix release notes for v0.60.0

### ISSUE THREAD

**Issue by kallangerard** [Snowflake-Labs/terraform-provider-snowflake#1784]
**Describe the bug**

The release notes for [v0.60.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.60.0) are invalidated to some unknown issue with the releaser integration. That's okay within itself, but currently there's no way to actually see what has been released across that release. For example if someone wants to upgrade from v0.59.0 to v0.60.0 or v0.61.0 there is no way to evaluate the changes.

**Expected behavior**

Correct Release notes even if it's a manual update, including future release note failures.

**Comment by carter293** [comment]
I agree

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
Fully agree that the release notes should always be correct. Right now, we're always checking them If they're correct and change them accordingly. The v0.60.0 is a pretty old version and we're expecting the majority of the users to be on newer versions, so please let us know If you're still using the older version and would see a value in changing linked release notes. For newer versions, we introduced a [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md) to specifically tell if there are any breaking changes and how to upgrade from version to version (that's why we always encourage upgrading to the latest version). If you are having any difficulties in upgrading from deprecated resources to new ones, please check our [guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) on that topic.
