### ISSUE TITLE
Wrong deprecation error for 'snowflake_grant_privileges_to_role' when dealing with grant USAGE to shares

### ISSUE THREAD

**Issue by simonepm** [Snowflake-Labs/terraform-provider-snowflake#2004]
**Provider Version**

0.69.0

**Terraform Version**

1.5.5

**Describe the bug**

While using  'snowflake_database_grant' and 'snowflake_schema_grant' resources to grant USAGE on a databases and schemas to a share, the following deprecation error is returned:

Γöé Warning: Deprecated Resource
Γöé   with snowflake_schema_grant.<redacted>,
Γöé   on main.tf line <redacted>, in resource "snowflake_schema_grant" "<redacted>":
Γöé <redacted>: resource "snowflake_schema_grant" "<redacted>" {
Γöé This resource is deprecated and will be removed in a future major version
**Γöé release. Please use snowflake_grant_privileges_to_role instead.**

**Expected behavior**

A new resource should be created allowing granting USAGE on database and schemas to a share, something like:

snowflake_grant_privileges_to_share

**Code samples and commands**

N/A

**Additional context**

snowflake_grant_privileges_to_role is not the right resource to be used to replace snowflake_schema_grant to a share.

We need snowflake_grant_privileges_to_share resource to be created before deprecating existing snowflake_database_grant and snowflake_schema_grant resources.

**Comment by sfc-gh-jcieslak** [comment]
Hey @simonepm
Previous grant resources cannot be mapped 1 to 1 to the new grant resources. That's why sometimes the proposed resource unfortunately may not be the correct one. The only thing we can do about it is to provide a list of new grant resources you may look into instead of one. Unfortunately, there's also no "smart" way of producing deprecated messages based on configuration (e.g. when x field is set => produce x message, and when y field is set => produce y message).

**Comment by simonepm** [comment]
No problem @sfc-gh-jcieslak , thanks, in the end with the latest versions of the provider we have 'snowflake_grant_privileges_to_share' now, I think this can be closed indeed!

**Comment by simonepm** [comment]
snowflake_grant_privileges_to_share available from version 0.85.0
