### ISSUE TITLE
database role grant, documentation , example, import - is missing

### ISSUE THREAD

**Issue by cpmub1** [Snowflake-Labs/terraform-provider-snowflake#2018]
**Provider Version**
0.69

**Describe the bug**

database role command & documentation/example/import for database role creation are missing

**Additional context**

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/database_role

**Comment by alexandrewatercare** [comment]
The last PR 0.70 added new database role grant in the SDK but I don't find any documentation how to use it. I try to understand the source code but I don't see how you use grantDatabaseRoleOptions in your database_role.go

**Comment by sfc-gh-asawicki** [comment]
@cpmub1, thanks for bringing this to our attention.

Docs were not appropriately generated because of the few typos, which were fixed in #2081. Changes will be visible in the docs with the next release.

@alexandrewatercare This functionality will be available (and adequately documented) as soon as we roll out the `snowflake_grant_datatabase_role` resource. We will work on it in October/November (check #1896 and #2024).
