### ISSUE TITLE
Unable to use securityadmin and useradmin roles in provider configuration

### ISSUE THREAD

**Issue by boseoladipo** [Snowflake-Labs/terraform-provider-snowflake#2062]
**Provider Version**

0.70.1

**Terraform Version**

Terraform v1.5.5

**Describe the bug**

Specifying the `securityadmin` or `useradmin` role in the provider configurations block leads to an error.

Example provider configuration:
```
provider "snowflake" {
  account  = "account_name"
  username = "terraform"
  password = "<redacted>"
  role      = "SECURITYADMIN"
}
```
After running plan:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: could not retrieve session id err = object does not exist or not authorized
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on provider.tf line 30, in provider "snowflake":
│   30: provider "snowflake" {
│ 
```
**Expected behavior**

Expected plan to run successfully using any role the specified user has access to 

**Additional context**

- The plan works fine if I use the `accountadmin` or `sysadmin` roles
- I get the same error when I set the default role for the user to `securityadmin` or `useradmin` and don't specify a role in the provider configurations

**Comment by alexey-vasin** [comment]
I'm seeing the same issue in our code - using roles other than `ACCOUNTADMIN` or `SYSADMIN` leads to an error.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
I've tried to reproduce this behaviour, but It worked perfectly fine on my end. The only way of getting the same error was when I put non existing role in the parameter, e.g. role = "this-role-doesnt-exist", so this error could also happen on misspelled role and I would be surprised if that is not the case, because even when I created a user that doesn't have SECURITYADMIN role granted I got this error:

`Error: could not retrieve session id err = Role 'SECURITYADMIN' specified in the connect string is not granted to this user. Contact your local system administrator, or attempt to login with another role, e.g. PUBLIC`

and I've tried with other different configurations, but none of them returned the error you've posted. Right now for me It seems like misspelled role or some misconfiguration than an issue with TF Provider. Let me know if you're still having this issue and I'll try to find out why this may happen.

**Comment by boseoladipo** [comment]
Hello
I have carefully checked the spelling, even copy pasted directly from snowflake but getting the same error.

I tried with a new user that does not have the SECURITYADMIN role granted, and got the error you mentioned.
```
╷
│ Error: could not retrieve session id err = 390186 (08004): Role 'SECURITYADMIN' specified in the connect string is not granted to this user. Contact your local system administrator, or attempt to login with another role, e.g. PUBLIC.
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on provider.tf line 29, in provider "snowflake":
│   29: provider "snowflake" {
│ 
╵
```
However, when I proceeded to grant that same user the SECURITYADMIN role, I got the previous error again.
```
╷
│ Error: could not retrieve session id err = object does not exist or not authorized
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on provider.tf line 29, in provider "snowflake":
│   29: provider "snowflake" {
```
Basically any role other than `ACCOUNTADMIN` or `SYSADMIN` does not work

**Comment by sfc-gh-jcieslak** [comment]
Ok, so I might have a clue what is the issue. I've been able to partially replicate the issue and you might have insufficient permissions (especially usage on warehouse which allows you to call session function) and that's why this error occurs. What is strange for me is that happens on default warehouse which I have to look into, but for now what you can do is create a warehouse assign permissions on it and use the terraform.
SQL for setting it up

```SQL
create user "test_tf" password = 'test123';
create warehouse test_wh;

grant role securityadmin to user "test_tf";

-- terraform plan still fails when user=test_tf, role=securityadmin, warehouse=test_wh

grant usage on warehouse test_wh to role securityadmin; -- this will allow us to call CURRENT_SESSION

-- terraform plan works now

revoke usage on warehouse test_wh from role securityadmin; -- won't work after this

-- cleanup
drop user "test_tf";
drop warehouse test_wh;
```

Terraform would look like
```
provider "snowflake" {
    account = "<your-acc>"
    username = "test_tf"
    password = "test123"
    role  = "securityadmin"
    warehouse = "test_wh"
}
```

Let me know if the workaround is working for you.

**Comment by boseoladipo** [comment]
It was indeed the warehouse! Granting usage on the warehouse to `SECURITYADMIN` solved the problem for me, thanks a lot!
