### ISSUE TITLE
Test before release

### ISSUE THREAD

**Issue by gbatiz** [Snowflake-Labs/terraform-provider-snowflake#2098]
**Provider Version**

Latest

**Terraform Version**

Latest

**Describe the bug**

Managing permissions, grants and users is a core use case, and if you have a look at the open issues, currently neither of them is possible:

- Users cannot be created (https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2058)
- The old grant resources are deprecated, the new one is unusable (filter issues for `snowflake_grant_privileges_to_role`)

**Would it be possible to test software before making a new release?**  
As a bare minimum test:

- Creating, modifying and destroying every resource
- Upgrading from the previous version

**Expected behavior**

- Upgrades from one version to the next always successful
- Deprecation warnings that can actually be resolved as the new resources are functional
- Core functionality reliably working
- Not releasing completely broken functionality

**Code samples and commands**

N/A

**Additional context**

I think the community would appreciate if Snowflake invested more resources to elevate the quality this provider, especially in light of the amount of money paid for the service.

**Comment by mlavaert** [comment]
I can only support this ticket. Upgrading the provider has caused multiple serious production issues in the past for us.

**Comment by sfc-gh-jcieslak** [comment]
Hey @[gbatiz](https://github.com/gbatiz) :wave:,
Thank you for taking the time to provide us with your feedback. We sincerely appreciate your input and understand your concerns. Your feedback is valuable to us as it helps us improve our services.
We would like to inform you that some of the points you have raised have already been addressed in our ongoing efforts to enhance our project. However, we would also like to let you know that as our project is still in the experimental phase, there are certain aspects that may not be immediately addressed.
One of them would be successful upgrades from one version to another. Because we are still in version 0.XX.0 ([Semantic Versioning](https://go.dev/doc/modules/version-numbers#v0-number)), we are still making breaking changes. We know that the provider is already used in many places in production, that’s why we try to minimize the number of them. In a case where breaking change is needed, we are adding a new entry in our [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#migration-guide) to help you with upgrading between the versions. After the 1.0.0 version (that we plan to reach around late fall this year), we will be able to ensure backward compatibility with the previous non-major versions.
To address other things point-by-point:
- Regarding all the points about grants and the old grant resources being deprecated - We had an ongoing initiative called [grants redesign](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#redesigning-grants) where we addressed most of the flaws and missing functionality in the new resources. Marking the old ones as deprecated enabled us to abandon the old implementation and support the new one. Then, in case of any missing functionality, we picked up those issues and addressed them as soon as possible.
- About the core functionality working as it should be - For the past few quarters [our plans](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap) were mostly about making the provider more stable. Our focus was scattered on certain aspects of the project that were all essential to get to the stable V1 version. This and the next quarter, we will address all of the [essential objects](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/ESSENTIAL_GA_OBJECTS.MD), and then follow up with the [remaining ones](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/REMAINING_GA_OBJECTS.MD). Also, during that we managed to help, fix, and resolve hundreds of issues, addressing them as they come and making the provider even more stable.
- Testing the provider - I think we have to partially agree on this one. The state of the provider going back a few quarters had many issues. Some of them are already addressed by [mentioned plans](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap), and others are addressed on a daily basis. The tests are in the second group where whenever we were doing any changes to a given object, we always added tests that would check added functionality. As time went on, we see that the number of tests in the provider drastically increased (and still will during the [preparation for V1](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap)) and the provider is more stable than ever before.

We genuinely appreciate your patience and understanding as we continue to make improvements. If you have any further suggestions or concerns, please do not hesitate to reach out to us. We value your input and are committed to ensuring your satisfaction.

**Comment by gbatiz** [comment]
Dear @sfc-gh-jcieslak ,

Thank you for answering my concern, I appreciate it!

We have decided to bite the bullet and upgrade from version 0.60something to 0.90.0 a month ago. We managed to replace 90% of the grant resources and resolve other deprecations with little disruption to our users.

I can confirm that the new resources are way more reliable, and in general there is a noticeable quality improvement of the provider. This is very much appreciated! Also, communication about the project has became a lot clearer and proactive, which is very nice.

Overall, nice to see that the concerns of the community are addressed. I think you guys are doing the right thing! 🚀
