### ISSUE TITLE
Error: The terraform-provider-snowflake_v0.72.0 plugin crashed!

### ISSUE THREAD

**Issue by gcyu** [Snowflake-Labs/terraform-provider-snowflake#2175]
**Provider Version**

v0.72.0

**Terraform Version**

Will update later.

**Describe the bug**

Terraform Snowflake plugin crashed when I tried to add another user to email recipient list of resource monitors during terraform apply.

**Expected behavior**

No error. 

**Code samples and commands**

terragrunt apply tf.plan

**Additional context**

Error screenshot:
![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/15685761/01ba9486-c649-4644-941a-2d40e4f2902c)

**Comment by gcyu** [comment]
I am actually waiting for the official fix of issue #2133 as the best long-term solution.
However, I tried to downgrade the provider version to v0.72.0 in order to not be blocked by issue #2133 . Then I encountered this plugin crash error. 
My code change is for adding a new Snowflake user to email recipient list of Snowflake resource monitors.

**Comment by sfc-gh-asawicki** [comment]
Hey @gcyu. Thanks for reporting the issue.

The problem you described is the same as in #2167. There is an incoming fix, #2287. We should release it shortly.

As for the authentication solution, please read here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2169#issuecomment-1816167117.

**Comment by abhi9342** [comment]
I have started observing crash for version 0.76.0.
I am receiving the following error message.


goroutine 107 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewDatabaseObjectIdentifierFromFullyQualifiedName({0xc000711810?, 0xc0015d0810?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/identifier_helpers.go:159 +0xcc
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.configureAccountRoleGrantPrivilegeOptions(0xc000d9b2e0?, {0xc0015c5630, 0x1, 0x1}, 0x1?, 0xc0009b4cf0)
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:715 +0x833
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateGrantPrivilegesToRole(0x0?, {0x1ced480?, 0xc000cd1860?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:456 +0x1ad
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x2054060?, {0x2054060?, 0xc0015bc2d0?}, 0xd?, {0x1ced480?, 0xc000cd1860?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007ad880, {0x2054060, 0xc0015bc2d0}, 0xc0015c6000, 0xc000e1f180, {0x1ced480, 0xc000cd1860})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0005ca048, {0x2054060?, 0xc0015bc0f0?}, 0xc000d9f770)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x2073560?, 0xc0005ca048?}}, {0x2054060, 0xc0015bc0f0}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x2053fb8?, {0x2054060?, 0xc001583da0?}, 0xc000d9f720)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0005a8320, {0x2054060?, 0xc001583590?}, 0xc0013bfb20)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:857 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1c998c0?, 0xc0005a8320}, {0x2054060, 0xc001583590}, 0xc0013bfab0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001792c0, {0x2063ec0, 0xc0002361a0}, 0xc001590360, 0xc000cc4ff0, 0x2d7e8d8, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1376 +0xdd2
google.golang.org/grpc.(*Server).handleStream(0xc0001792c0, {0x2063ec0, 0xc0002361a0}, 0xc001590360, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1753 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.2/server.go:998 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.58.2/server.go:996 +0x18c

Error: The terraform-provider-snowflake_v0.76.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
