### ISSUE TITLE
snowflake resources import - snowflake_sequence_grant

### ISSUE THREAD

**Issue by pogorzem92** [Snowflake-Labs/terraform-provider-snowflake#2199]
**Provider Version**

0.67

**Terraform Version**

0.13.7

**Describe the bug**
I got error during importing resources to terraform:

Error: unexpected format of ID ("DATABASE|SCHEMA||OWNERSHIP|false|true|role"), expected database_name|schema_name|sequence_name|privilege|with_grant_option|on_future|roles

**Expected behavior**

resource should be imported

**Code samples and commands**

terraform import --var-file=dev.tfvars module.snowflake_bi_stack.module.schemas.snowflake_sequence_grant.o_sequence[\"NAME\"] "DATABASE|SCHEMA||OWNERSHIP|false|true|role"

**Additional context**

import didn't work correctly and error message suggest that code it fine
I tried add one field in ID and it worked - it looks like code needed additional 'on_all' field in ID - added fight before roles name - documentation and ERROR on console doesn't mention it

terraform import --var-file=dev.tfvars module.snowflake_bi_stack.module.schemas.snowflake_sequence_grant.o_sequence[\"NAME\"] "DATABASE|SCHEMA||OWNERSHIP||false|true|role"

I got similar errors with other resources: snowflake_task_grant and snowflake_stream_grant - probably issue is the same

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋
Closing, as the issue was about the deprecated/not allowed functionality. Recently, we released [a new grant resource](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_ownership) which is capable of granting ownership. Please, give it a try. If there will be any issues with it, create another GitHub issue. Also, please check our [technical documentation section](https://github.com/Snowflake-Labs/terraform-provider-snowflake/tree/main/docs/technical-documentation) where you can find a migration guide that can help you with upgrading to the latest grant resources and our newly added design decision doc (regarding new grant resources).
