### ISSUE TITLE
pipe  creation error with "object does not exist or not authorized" dependent from External Stage that seems not to be fully available 

### ISSUE THREAD

**Issue by toni-moreno** [Snowflake-Labs/terraform-provider-snowflake#2587]
### Terraform CLI and Provider Versions

Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.86.0

### Terraform Configuration

```terraform
This is not a config related behaviour it seems related on how long provider is waitting until a dependant resource is fully created and available.

we have detected this behaviour several times with diferent resources not only pipes and stages.
```

### Expected Behavior

This is not a config related behaviour it seems related on how long provider is waitting until a dependant resource is fully created and available.

we have detected this behaviour several times with diferent resources.

in my case the error was creating a pipe.
```bash
...
...
module.bscrm.module.sfbs.snowflake_stage.stage["DES_XXX.PUBLIC.EXTERNAL_XXXX"]: Creation complete after 1s [id=DES_XXX|PUBLIC|EXTERNAL_XXX]
....
...
...
╷
│ Error: [errors.go:17] object does not exist or not authorized
│ 
│   with module.bscrm.module.sfbs.snowflake_pipe.pipe["DES_XXX.SCHEMA.MY_PIPE"],
│   on ../../modules/snowflake_bs_v3/pipe.tf line 35, in resource "snowflake_pipe" "pipe":
│   35: resource "snowflake_pipe" "pipe" {
│ 
╵
```

we have reviewd the exact query with the error.

![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/5883405/9b7d0270-e945-4dad-9692-f8f395a3814f)

The error in the console was "SQL compilation error: Stage "DES_XXX.PUBLIC.EXTERNAL_XXX des not exist or not authorized"

But I've reviewed and in fact the object exist.

![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/5883405/d3236713-3788-4678-ac28-4e9d79644ab2)

Without any change .. we have executed again `terraform apply`

and after this apply  the config has been deployed ok.

```bash
...
Apply complete! Resources: 18 added, 0 changed, 0 destroyed.
```

It seems like terraform executes dependent resources too fast or may be it shoult validate the object creation before continuing working on dependent resources ( in this case the problem was the stage)

### Actual Behavior

The resources should be created in the first  `terraform apply`

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @toni-moreno. Thanks for reaching out to us.

This is not that obvious that any await should be implemented in this case inside the terraform provider. Reasons against it:
- there is no mention in SF docs about any time that should pass before the object is being available https://docs.snowflake.com/en/sql-reference/sql/create-stage (e.g. for the account it is explicit: https://docs.snowflake.com/en/sql-reference/sql/create-account#usage-notes)
- from your output, I understand that the external stage was created successfully and the problem occurred for the pipe creation; it means that the SHOW STAGES and DESCRIBE STAGE commands were run successfully (otherwise provider would have returned a different error: "Failed to describe stage" or "Failed to show stage by id"); we are limited to the responses we can get from executing SF SQL statements, so if these two run without error then it's hard to wait for anything (besides waiting an arbitrary number of seconds); we can't wait e.g. for accessing the URL used for creation because there is no guarantee that it will be accessible from the machine where tf is executed
- if re-running the plan/apply helps then it means that the behavior is aligned with terraform eventual convergence

Additionally, config matters; you have to have dependency between stage and pipe; the error you showed may be caused also by the lack of stage-pipe dependency, so please make sure you have it explicit in your config.

**Comment by sfc-gh-asawicki** [comment]
Hey @toni-moreno. Closing the issue due to the rationale presented above.
