### ISSUE TITLE
snowflake_grant_account_role mixed role_name and parent_role_name

### ISSUE THREAD

**Issue by lvrbanec** [Snowflake-Labs/terraform-provider-snowflake#2734]
### Terraform CLI and Provider Versions

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.76"
    }
  }

### Terraform Configuration

```terraform
terraform version
Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.41.0
+ provider registry.terraform.io/snowflake-labs/snowflake v0.87.2
```

### Expected Behavior

Based on documentation terraform should grant parent_role_name to role_name

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role
##################################
grant account role to account role
##################################

resource "snowflake_role" "role" {
  name = var.role_name
}

resource "snowflake_role" "parent_role" {
  name = var.parent_role_name
}

resource "snowflake_grant_account_role" "g" {
  role_name        = snowflake_role.role.name
  parent_role_name = snowflake_role.parent_role.name
}

### Actual Behavior

Parent and child roles are mixed. Instead of granting parent to child, terraform grants child to parent. 

### Steps to Reproduce

In Terraform 
```
resource "snowflake_role" "A" {
  name                                = "A"
  provider                            = snowflake.user_admin
}

resource "snowflake_role" "B" {
  name                                = "B"
  provider                            = snowflake.user_admin
}

resource "snowflake_grant_account_role" "A_TO_B" {
  provider  = snowflake.security_admin
  role_name = "B"
  parent_role_name = "A"
}
```
In snowflake
`SHOW GRANTS TO ROLE A;
`
<img width="1470" alt="image" src="https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/79400612/b02014f0-89ac-4f34-a174-49354795ae31">

### How much impact is this issue causing?

High

**Comment by sfc-gh-jcieslak** [comment]
Hey @lvrbanec 👋 
Not sure what this is about. The `snowflake_grant_account_role` resource is mimicking what's available on Snowflake ([here's the documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-role)). I would say this is a normal behavior that a child role is granting to the parent role because it's giving the parent role the same grants as the child one.  Here's a more detailed article on how Snowflake's access management works: https://docs.snowflake.com/en/user-guide/security-access-control-overview. Please, let me know If you're concerned that there's something wrong with the provider. Ideally, please link Snowflake documentation saying the connection should be reversed to the one we have right now.

**Comment by lvrbanec** [comment]
Hey @sfc-gh-jcieslak
Thanks for the answer. You are right, I expected that Snowflake would show parent to child. I totally misread the documentation cause of my expectations. Many many thanks for clearing it out for me and spending your time looking into this issue. 

Wish you all the best

**Comment by lvrbanec** [comment]
Resolved
