### ISSUE TITLE
[Bug]: snowflake_grant_account_role fails on apply due to Root resource was present, but now absent.

### ISSUE THREAD

**Issue by kcarrillorhoads** [Snowflake-Labs/terraform-provider-snowflake#2848]
### Terraform CLI Version

1.5.3

### Terraform Provider Version

0.91.0

### Terraform Configuration

```terraform
resource "snowflake_grant_account_role" "service_bot_id_roles" {
  provider  = snowflake.id
  for_each  = toset(local.id_snowflake_bot_roles)
  role_name = each.value
  user_name = module.service_bot_id_name[0].user_name
}

### This for_each pattern works in other places but when packaged in module fails.
```

### Category

category:grants

### Object type(s)

resource:grant_account_role

### Expected Behavior

I would expect that the resource would be created for each of the existing roles passed in the for_each statement to the explicitly provided user_name.

### Actual Behavior

The plan looks entirely normal but upon apply the following error occurs.

 produced an unexpected new value: Root resource was
│ present, but now absent.

Here's a debug file with security keys and tokens removed.
[apply_failure.txt](https://github.com/user-attachments/files/15538835/apply_failure.txt)

### Steps to Reproduce

This may be a result of leveraging an in repo module which implements this.  However I have found that this unique case I am seeing a plan that looks exactly what I want:

  # module.service.snowflake_grant_account_role.service_bot_id_roles["PUBLIC"] will be created
  + resource "snowflake_grant_account_role" "service_bot_id_roles" {
      + id        = (known after apply)
      + role_name = "PUBLIC"
      + user_name = "SERVICE_DEIDDEV_BOT"
    }

But upon apply the apply fails.

### How much impact is this issue causing?

Medium

### Additional Information

I am unable to understand the

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment]
Hey @kcarrillorhoads 👋 
It's happening, because the `PUBLIC` role is a "pseudo-role" (more on that [here](https://docs.snowflake.com/en/user-guide/security-access-control-overview#system-defined-roles)) that is already assigned to every role and user, so there's no need to grant it through terraform. If you're having an issue with removing the resources please use `terraform state rm <id>` to remove the resource from the state (and you can safely remove the configuration). Also, for a test, I granted the `PUBLIC` role to myself in the worksheet and got this message: "Granting role PUBLIC has no effect.  Every user and role has role PUBLIC implicitly granted.".

**Comment by sfc-gh-jcieslak** [comment]
Closing due to long inactivity (\+ not really a bug, but rather general misuse of Snowflake/Provider)
