### ISSUE TITLE
[Feature]: Improve documentation for snowflake_grant_privileges_to_account_role

### ISSUE THREAD

**Issue by bdumford-OM1** [Snowflake-Labs/terraform-provider-snowflake#2994]
### Use Cases or Problem Statement

This is not a huge deal, but could the documentation for [snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role) be improved?  Specifically, there needs to be better documentation for how to migrate from the deprecated [snowflake_procedure_grant](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.92.0/docs/resources/procedure_grant) resource to `snowflake_grant_privileges_to_account_role`.

When migrating from the `snowflake_procedure_grant` resource, it was not at all obvious as to where to put the [argument_data_types](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.92.0/docs/resources/procedure_grant#argument_data_types).  After a lot of searching, I found the answer in issue #2375 and on the [CREATING_ISSUES](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CREATING_ISSUES.md#granting-on-functions-or-procedures) page.  Since there is a solution available, it would make sense to document it in the appropriate places.

### Category

category:other

### Proposal

An example for migrating from the `snowflake_procedure_grant` should be added to the [MIGRATION_GUIDE](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md).  Additionally, an example like the one [here](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2375#issuecomment-1915553094) should be added to the Terraform registry [page](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role) for `snowflake_grant_privileges_to_account_role`.

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @bdumford-OM1 👋 Thanks for the feedback. These things can be added to our docs. Currently we're reworking essential objects on our road to v1. We welcome community contributions based on our [contribution guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CONTRIBUTING.md).

MIGRATION_GUIDE is updated manually, and `snowflake_grant_privileges_to_account_role ` example is located in `examples/resources/snowflake_grant_privileges_to_account_role/resource.tf`.

**Comment by sfc-gh-jmichalak** [comment]
Hi, we've released [v0.96.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.96.0), which adjusts the documentation.

We've added an example to https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/guides/identifiers. Also, we've decided not to include a separate example in `snowflake_grant_privileges_to_account_role` because now we highly recommend using `<resource_name>.fully_qualified_name` to reference other objects. All of the examples were adjusted to use this field and we added an entry to [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#new-fully_qualified_name-field-in-the-resources) about this change. But we left a note below that instead of using this new field, IDs can be constructed manually by hand, like before.

Let us know if this works for you!

**Comment by sfc-gh-jmichalak** [comment]
Closing the issue due to inactivity. Please create a new one if you have more suggestions.
