### ISSUE TITLE
[Feature]: Add ENFORCE_NETWORK_RULES_FOR_INTERNAL_STAGES parameter

### ISSUE THREAD

**Issue by yuukiyamanaka** [Snowflake-Labs/terraform-provider-snowflake#3116]
### Use Cases or Problem Statement

When I tried to set `ENFORCE_NETWORK_RULES_FOR_INTERNAL_STAGES` parameter using `snowflake_account_parameter` resource,

```
resource "snowflake_account_parameter" "enforce_network_rules_for_internal_stages" {
  key   = "ENFORCE_NETWORK_RULES_FOR_INTERNAL_STAGES"
  value = "true"
}
```

I encounter the below error:
```
Error: Invalid object parameter: ENFORCE_NETWORK_RULES_FOR_INTERNAL_STAGES

with snowflake_account_parameter.enforce_network_rules_for_internal_stages
```

### Category

category:resource

### Object type(s)

resource:account_parameter

### Proposal

I think this parameter is still in public preview, so the provider does not support it yet.
Do you have plans to add this parameter? If not, I would like to submit a PR.

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @yuukiyamanaka. Thanks for reaching out to us.

We will shortly visit the rework of `snowflake_account` and `snowflake_account_parameter` resources (check https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/ESSENTIAL_GA_OBJECTS.MD and https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/REMAINING_GA_OBJECTS.MD). We will add this parameter then.

One more important thing to mention: as I can see in the docs https://docs.snowflake.com/en/sql-reference/parameters#enforce-network-rules-for-internal-stages, this parameter is currently in public preview. We focus on the generally available features in this provider because the preview features tend to change.

Before adding this parameter, you can also use the [snowflake_unsafe_execute resource](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute) to set this parameter through terraform.

**Comment by yuukiyamanaka** [comment]
Thank you for response!
I understand the current situation.

**Comment by sfc-gh-jmichalak** [comment]
Hi @yuukiyamanaka 👋 

This has been added in v1.0.1 ([migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v100--v101), [release](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v1.0.1)). Please upgrade to this version and move from `unsafe_execute` (in v1, it's `execute`) to `account_parameter`.
