### ISSUE TITLE
[Feature]: snowflake_grant_database_application_role

### ISSUE THREAD

**Issue by yuukiyamanaka** [Snowflake-Labs/terraform-provider-snowflake#3134]
### Use Cases or Problem Statement

When I want to setup account budget using the [docs](https://docs.snowflake.com/en/user-guide/budgets/config#activate-and-set-up-the-account-budget-using-sql), I need to quary the below:
```
GRANT USAGE ON INTEGRATION budgets_notification_integration
  TO APPLICATION snowflake;
```

I cannnot the terraform resource for this.
According to [this docs](https://docs.snowflake.com/ja/sql-reference/sql/create-application-role), Application role has already Generally Avaialble.

The latest version only support **snowflake_grant_application_role**.
Do you have roadmap for supporting **snowflake_application_role** and **snowflake_grant_database_application_role** resources?

### Category

category:resource

### Proposal

Implement

- **snowflake_application_role**  resouce for `CREATE/ALTER/DROP APPLICATION ROLE`
- **snowflake_grant_database_application_role** resouce for `GRANT xxx TO APPLICATION xxx`

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [X] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @yuukiyamanaka 👋 
We have Application Roles on our roadmap - in the [Remaining Objects list](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/REMAINING_GA_OBJECTS.MD) (as part of preparing GA objects for v1). We'll start working on this after we conclude the [essential objects](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/ESSENTIAL_GA_OBJECTS.MD), but we don't have a release date yet.

As a workaround, you can use the [unsafe_execute](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute) resource.

**Comment by yuukiyamanaka** [comment]
@sfc-gh-jmichalak 

Thank you for your reply.
I have two questions.

1. If I were to implement a **snowflake_application_role** and submit a PR, would it be possible to have it merged?
2. I understand that setup scripts should be used for application roles. On the other hand, if we want to grant permissions to a "Snowflake" Application, as in the Budget example above, is it possible to make changes to the setup script?

**Comment by sfc-gh-jcieslak** [comment]
Hey @yuukiyamanaka 👋 
Both commands are not available to be run fully outside of the application context (setup script) that's why it doesn't make much sense to have it as a terraform resource (because you don't have many options on running those commands). For granting privileges to application roles you can [read this](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege-application-role#access-control-requirements). For granting application roles [read this](https://docs.snowflake.com/en/sql-reference/sql/grant-application-role#usage-notes). The research on grants was done a pretty long time ago, but maybe when we'll come back to them it will be possible to create such resources. Right now, we focus on other tasks to provide the V1 version of the provider.

**Comment by yuukiyamanaka** [comment]
@sfc-gh-jcieslak 
Thank you for your reply.
I fully understand. Thank you! 👏
