### ISSUE TITLE
Change browser based authentication to open one or the lowest minimum number of required browser tabs instead of too many per a single run

### ISSUE THREAD

**Issue by dlawrences** [Snowflake-Labs/terraform-provider-snowflake#759]
**Is your feature request related to a problem? Please describe.**

When running `terraform plan` or `terraform apply`, the provider will open a high number of browser tabs. It seems like it may be doing browser-based authentication for each resource you are trying to deploy (or close to this parity). This becomes problematic when trying to test the migration of an existing Snowflake database, for example.

**Describe the solution you'd like**

Require one or the lowest minimum number of browser tabs to be opened to not potentially crash the client machine.

**Describe alternatives you've considered**

One can always use password-based or key-based authentication, but for teams that want to govern Snowflake access based on SSO, this is a problem.

**Additional context**

N/A

**Comment by dlawrences** [comment]
Also confirmed in https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/199#issuecomment-635779759

**Comment by dlawrences** [comment]
Team, any updates?

**Comment by sfc-gh-swinkler** [comment]
Hello @dlawrences . I have looked into this issue and I do not believe it is any problem with the Terraform provider, but rather with the golang connector. You see, there is a database driver that has a pool of connections to allow for concurrency. Whenever a new connection is needed, it is created on demand. Normally this is not a problem, except for the way the golang connector works if browser authentication method is selected, it will go through the full SAML workflow to exchange tokens, and there is no session persistence of these tokens in the driver. A very easy way to replicate the issue is the following script:
```
package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"regexp"
	"time"

	"github.com/luna-duclos/instrumentedsql"
	"github.com/snowflakedb/gosnowflake"
)

func init() {
	re := regexp.MustCompile(`\r?\n`)

	logger := instrumentedsql.LoggerFunc(func(ctx context.Context, msg string, keyvals ...interface{}) {
		s := fmt.Sprintf("[DEBUG] %s %v\n", msg, keyvals)
		log.Println(re.ReplaceAllString(s, " "))
	})

	sql.Register("snowflake-instrumented", instrumentedsql.WrapDriver(&gosnowflake.SnowflakeDriver{}, instrumentedsql.WithLogger(logger)))
}

func main() {
	// Create a new Snowflake connection
	config := &gosnowflake.Config{
		Account: "MY_SF_ACCOUNT",
		User:    "someuser@example.com",
		Database:      "TEST",
		Role:          "ACCOUNTADMIN",
		Authenticator: gosnowflake.AuthTypeExternalBrowser,
	}
	dsn, err := gosnowflake.DSN(config)
	if err != nil {
		panic(err)
	}
	fmt.Printf("dsn: %s\n", dsn)
	db, err := sql.Open("snowflake-instrumented", dsn)
	if err != nil {
		panic(err)
	}

	fmt.Printf("db opened\n")

	for i := 0; i < 10; i++ {
		runQuery(db)
	}
}

func runQuery(db *sql.DB) {
	fmt.Printf("running query\n")
	rows, err := db.Query("select * from employee_table")
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v", rows)
}
```

this script will make 10 requests to API, using 10 different connections (because it favors creating fresh connections if there is space for it). And it will open 10 browser windows to authenticate. I will bring this up with the go connector team. I see that there was a feature to support [reusing connections for ODBC, JDBC and Python connectors](https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#using-connection-caching-to-minimize-the-number-of-prompts-for-authentication-optional). So we should be able to do the same for the golang connector. 

My belief is the problem lies here: https://github.com/snowflakedb/gosnowflake/blob/5da2ab2463b2c7e544722bc58defdb23397287d6/connector.go#L11-L14. There should be a caching of SSO tokens here, so when `Connect()` function is called, it can reuse those rather than going through full SSO workflow to fetch its own tokens.

**Comment by dlawrences** [comment]
Thanks, @sfc-gh-swinkler, that makes sense. It doesn't seem there is anything that can be done in the meantime since the Go Snowflake driver doesn't seem to use, as you pointed out, token caching as other drivers/libraries do per https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#using-connection-caching-to-minimize-the-number-of-prompts-for-authentication-optional. 

Could you please add the ticket in here when you come around on raising the bit with the Go Snowflake Driver team? That would be much appreciated
