### ISSUE TITLE
Support Custom OAuth Integration Type

### ISSUE THREAD

**Issue by dapearce** [Snowflake-Labs/terraform-provider-snowflake#785]
**Is your feature request related to a problem? Please describe.**

I need to support a custom OAuth security integration for Retool

**Describe the solution you'd like**

Ability to specify "CUSTOM" with `oauth_client_type` and `oauth_redirect_uri` parameters when defining a `snowflake_oauth_integration` resource.

**Describe alternatives you've considered**

Manually managing this or using password-based auth for this connection.

**Additional context**

Recently it looks like the `snowflake_oauth_integration` resource was added (https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/763). Which is great. It doesn't support `CUSTOM` OAuth types though, which requires only a couple additional (optional) properties: https://docs.snowflake.com/en/sql-reference/sql/create-security-integration.html#snowflake-oauth-custom-client-parameters

I need this to support an OAuth connection for Retool, which only has password or custom OAuth connection options.

**Comment by kramer1007** [comment]
+1 for this feature request. 

Here is a real-world example requirement:
https://docs.popsql.com/docs/connecting-to-snowflake

`
-- Create OAuth security integration
create or replace security integration popsql
  type = oauth
  enabled = true
  oauth_client = custom
  oauth_client_type = 'CONFIDENTIAL'
  oauth_allow_non_tls_redirect_uri = true
  oauth_redirect_uri = 'https://popsql.com/users/auth/snowflake_oauth2/callback'
  oauth_issue_refresh_tokens = true
  oauth_refresh_token_validity = 86400;

-- Get the client ID and secrets. Note the integration name must be uppercase here
select system$show_oauth_client_secrets('POPSQL');

-- Describe the security integration
-- In order to successfully use refresh tokens, ensure `PRE_AUTHORIZED_ROLES_LIST` is empty
describe security integration popsql;
`

**Comment by Spince** [comment]
Looker also requires a redirect uri

**Comment by bburner** [comment]
this is also needed for integration with dbt.

**Comment by jmak123** [comment]
Same here, needed for Snowflake REST API token

**Comment by troyel** [comment]
+1 - in addition to "CUSTOM" what is stopping me from using this now is the missing "oauth_client_type" field. Same issue as #1421 Thanks!
